# Site
name: "Mihrabad Yayınları"
title: "Mihrabad Yayınları"
description: "Geçmiş tarihi, bügünü ve yarını romanlarıyla yorumlayan ve bu konuları en iyi şekilde bizlere aktaran yayınevi."
meta_description: "Mihrabad Yayınları"
dolinkpage: https://e-damla.ams3.digitaloceanspaces.com/damlayayinevi_ornek_sayfalar/
mlink: https://www.damlayayinevi.com.tr/go?sku=
damla-link: https://www.damlayayinevi.com.tr/mihrabad-yayinlari
end: /index.html
meserimglink: asseets/images/meser-bas/
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'iletisim@damlayayinevi.com.tr'
google_analytics: 'UA-53710816-10'
disqus: 'mihrabadyayinlari'
permalink: "/:title/"
instagram: https://www.instagram.com/mihrabadyayin/
facebook: https://tr-tr.facebook.com/mihrabadyayin/
twitter: https://twitter.com/mihrabadyayin


# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge

gem:
    -jekyll-sitemap